CREATE TRIGGER tr_BooksINSERTorUPDATE ON Books
AFTER UPDATE,INSERT
AS
UPDATE Books
SET BookName = UPPER(LEFT(BookName,1)) + LOWER(SUBSTRING(BookName,2,LEN(BookName)))
WHERE ID = (SELECT ID FROM inserted)
GO